### ISSUE TITLE
Multiple errors handling for edit command not comprehensive

### ISSUE THREAD

**Issue by cth06-Github** [AY2425S1-CS2103-F09-1/tp#142]
![image](https://github.com/user-attachments/assets/b46a95db-8453-4c18-9e15-c632a4fa1675)
^2 errors are shown here <br> (missing index and wrong role name)

Either we show all the errors (hard), or errors detected should go from left to right.

**Comment by somethingfishyfishy** [comment]
![image](https://github.com/user-attachments/assets/df15395e-dfe7-4d4b-b913-82bc7e6ca450)

Fixed closing issue
