### ISSUE TITLE
Role should be an optional field in add command

### ISSUE THREAD

**Issue by LowXiSi** [AY2425S1-CS2103-F09-1/tp#152]
Role is a compulsory field in add command, however in a normal CCA there are likely members who do not hold any roles.

<img width="736" alt="Screenshot 2024-10-28 at 9 55 40 PM" src="https://github.com/user-attachments/assets/5adc8353-a8e4-45fc-9bfc-d8a5cbe405de">

It may be more intuitive for roles to be optional.

**Comment by cth06-Github** [comment]
Oh, maybe we were looking at a particular kind of CCA -- where each member must hold a role/department. There is no such thing as "general member". If we want to broaden the definition of the CCA, maybe we can add a role called "General". If we have a "General", we should have a mechanism that says if a member is assigned with "General", no other roles should be assigned to the member.

**Comment by somethingfishyfishy** [comment]
I think "Member" instead of "General" would be better. For simplicity, I think mandating that "r/" be specified is important. As a future update (developer guide), we can include optional parameter for roles but if not specified, automatically set to member
