### ISSUE TITLE
[PE-D][Tester C] [Add] Cannot add same name when there is no nickname

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-1/tp#235]
User guide did not mention that same name cannot be added when there is no nickname. Users can be confused.

![image.png](https://raw.githubusercontent.com/jowhee3011/ped/main/files/1a6b271d-71dd-4a4f-9b91-4f18414cb382.png)

![image.png](https://raw.githubusercontent.com/jowhee3011/ped/main/files/9502ff75-32a9-4087-aa35-299df14c40d6.png)

Suggestion: Can indicate clearer in the user guide.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jowhee3011/ped#1

**Comment by somethingfishyfishy** [comment]
Fix by adding in UG astericks

say if original input has no nickname, if inputting same name, nickname must be non empty

**Comment by somethingfishyfishy** [comment]
Related to #255
