### ISSUE TITLE
[PE-D][Tester B] Inconsistent error messages when editing nicknames with duplicates

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-1/tp#237]
There is some discrepancies when editing to create duplicate nicknames. The error message for the other duplicate cases mention nickname as an example but the actual duplicate nickname error message does not use that.

Users with the same full name, with one being assigned a duplicate nickname:
![image.png](https://raw.githubusercontent.com/itsme-zeix/ped/main/files/00cd4112-898a-4ca0-a705-e6b192c2f9eb.png)

Users being assigned a duplicate email results an error message that describes duplicate 'nicknames' as a potential case, but that message is not assigned to the case of duplicate nicknames
![image.png](https://raw.githubusercontent.com/itsme-zeix/ped/main/files/9d74b829-99a0-4b76-a286-27ac9e9a5af5.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: itsme-zeix/ped#1

**Comment by somethingfishyfishy** [comment]
See Issue #255
