### ISSUE TITLE
[PE-D][Tester D] Formatting issue of header Delete by name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-1/tp#243]
![image.png](https://raw.githubusercontent.com/slye20/ped/main/files/21f00cf5-7212-428f-9bb3-c645838bf50c.png)

It seems like the whole header should be orange, but in this case, only the last letter is orange

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: slye20/ped#1

**Comment by somethingfishyfishy** [comment]
Interesting. I think have to print from chrome, and the most updated version. And also have to let it refresh??

![image](https://github.com/user-attachments/assets/2699e89c-6b95-4eb5-9005-c82c0a5914e4)

**Comment by somethingfishyfishy** [comment]
Refer to #259
