### ISSUE TITLE
[PE-D][Tester C] [Role] Can have more than one role containing President

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-1/tp#245]
It is possible for me to allocate President and Vice President to a person. In reality, it is almost impossible for this to happen. Would be better if this case can be considered.

![image.png](https://raw.githubusercontent.com/jowhee3011/ped/main/files/3857f57b-5bb3-4096-a01d-8f531cf8d306.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jowhee3011/ped#2

**Comment by somethingfishyfishy** [comment]
Responded

![image](https://github.com/user-attachments/assets/ea7f5b42-2269-45fa-97c3-834d61ff1109)
