### ISSUE TITLE
[PE-D][Tester B] `list contacts all` displays all contacts 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-1/tp#250]
In the `help list` message, there are 3 available commands for list specified:
-  `list`
- `list contacts`
- `list all contacts`

![image.png](https://raw.githubusercontent.com/itsme-zeix/ped/main/files/622adc32-c72d-4158-b474-af9cb1294261.png)

However, `list contacts all` also functions in listing all contacts. The image below shows the output after using `list contacts all`. Perhaps we could just catch this case or include `list contacts all` as a possible option in listing contacts! Should be an easy fix!
![image.png](https://raw.githubusercontent.com/itsme-zeix/ped/main/files/82e3da75-c086-45b5-98b5-cb8f71b7ac43.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: itsme-zeix/ped#6

**Comment by cth06-Github** [comment]
* write in known issue & plan enhancements
* list, [all]* [contacts]*
* change user guide

**Comment by WinstonJin** [comment]
Just change UG, Im not adding into the Planned Enhancements

**Comment by somethingfishyfishy** [comment]
User guide done, waiting Tse Hui

**Comment by WinstonJin** [comment]
Added into user guide, will close along the PR
