### ISSUE TITLE
[PE-D][Tester C] [ERROR MESSAGE] Inaccurate Error Message

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-1/tp#255]
The command will not result in a contact that already exists in the address book. It only results in  contacts with same names, but their other fields are different.

![image.png](https://raw.githubusercontent.com/jowhee3011/ped/main/files/1b8d79e8-23ec-4072-bc32-6ea63c14d6ce.png)

Can stick to this error message, since nicknames are covered here too.
![image.png](https://raw.githubusercontent.com/jowhee3011/ped/main/files/a63389a8-d72d-40b7-9094-473dbb2e2eb6.png)

If unchanged, users may be left confused as they believe that they are not keying in the same contact.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jowhee3011/ped#5

**Comment by cth06-Github** [comment]
* known issue, enhancement (to standardise)
* need to edit the grammar for first meessage

**Comment by somethingfishyfishy** [comment]
UG for Edit

![image](https://github.com/user-attachments/assets/83dda15b-77e7-48e7-a623-1d277f62bfd8)

Invalid contacts:
![image](https://github.com/user-attachments/assets/fac691b7-9469-4700-abd7-ae2416517c93)
