### ISSUE TITLE
[PE-D][Tester B] Using a `find <NAME1>` followed by `delete <NAME2>` incorrectly suggests that a user with <NAME2> does not exist in the address book

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-1/tp#270]
In a contact list containing `Edward Clark`, after using `find n/ Christopher` followed by `delete Edward Clark`, the following error incorrectly suggests that `Edward Clark` does not exist. Perhaps the error message or user guide can be updated to reflect that `delete <NAME>` can only apply to the users who are currently displayed on the list

![image.png](https://raw.githubusercontent.com/itsme-zeix/ped/main/files/1d141e6c-3978-4e20-8a3d-a0c1ee897ea1.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: itsme-zeix/ped#14

**Comment by cth06-Github** [comment]
if (targetIndex == null) {
            screenDuplicate(allContactList);
            setTargetIndex(allContactList);
            // System.out.println("Have set Target Index: " + targetIndex);
            if (targetIndex.getZeroBased() >= allContactList.size()) {
                throw new CommandException(Messages.MESSAGE_INVALID_CONTACT_DISPLAYED_INDEX);
            }

            contactToEdit = allContactList.get(targetIndex.getZeroBased());
            editedContact = createEditedContact(contactToEdit, editContactDescriptor);
        } else {
            assert (targetIndex != null);

            setTargetIndex(lastShownFilteredList);
            if (targetIndex.getZeroBased() >= lastShownFilteredList.size()) {
                throw new CommandException(Messages.MESSAGE_INVALID_CONTACT_DISPLAYED_INDEX);
            }
