### ISSUE TITLE
[PE-D][Tester C] [PAGE] Deleting (or editing) a contact with duplicated names is inconvenient

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-1/tp#272]
User may be unsure about why there is a duplicate, and will have to navigate the different pages on their own before they can identify the specific contact they wish to delete.

[Address App 2024-11-08 17-14-01.zip](https://raw.githubusercontent.com/jowhee3011/ped/main/files/5f944e5c-fdbd-43a7-b2d6-decdae471da3.zip)

This can cause user frustration especially when the contact book is larger.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jowhee3011/ped#9

**Comment by cth06-Github** [comment]
in user guide say how to do in a more effieicnt method

**Comment by somethingfishyfishy** [comment]
Related to #262
