### ISSUE TITLE
[PE-D][Tester A] Cosmetic flaw, colour of header of name in UG is inconsistent

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F09-1/tp#275]
![image.png](https://raw.githubusercontent.com/ethantyh692/ped/main/files/283b10a8-5747-4db2-b111-74f3d5e3ccb3.png)

Only the `e` in `name` is orange while the rest are black

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ethantyh692/ped#15

**Comment by somethingfishyfishy** [comment]
Same as #259
