### ISSUE TITLE
(on actual submission) Ensure PDF Formatting for both User and Developer Guide

### ISSUE THREAD

**Issue by cth06-Github** [AY2425S1-CS2103-F09-1/tp#304]
Checklist to do:

- [ ] No weird colour problems
- [ ] No images are cut off
- [ ] ALL Hyperlinks are working (go to correct page as intended)
- [ ] Allow copying of text
- [ ] It's "paginated" (not sure how to do it with the current conversion technique we're supposed to do) if "paginated" means showing page numbers)
- [ ] Reasonable size (e.g. A4)
- [ ] Reasonable File size: < 15 MB
- [ ] File size not unbloated necessarily (e.g. image too high a required resolution)
- [ ] PDF Friendly: Don't use expandable panels, embedded videos, animated GIFs etc.

<img width="544" alt="image" src="https://github.com/user-attachments/assets/9e096df7-077d-4a12-9e50-f679752ed227">
<br>Link: https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html

<img width="326" alt="image" src="https://github.com/user-attachments/assets/7c51b248-5cbb-440f-811f-a342b72b78b1">
<img width="408" alt="image" src="https://github.com/user-attachments/assets/1926fcb3-574d-4bab-89d0-feb76bad0504">
<img width="326" alt="image" src="https://github.com/user-attachments/assets/2875de15-28d2-4d6f-a039-7a2039617744">
<br>Link: https://nus-cs2103-ay2425s1.github.io/website/admin/tp-constraints.html

**Comment by WinstonJin** [comment]
Related to issues:
#239 
#259 
#269 
#291
