### ISSUE TITLE
Is this considered lacking of context?

### ISSUE THREAD

**Issue by cth06-Github** [AY2425S1-CS2103-F09-1/tp#352]
<img width="617" alt="image" src="https://github.com/user-attachments/assets/11f5dfa5-e6f2-44cc-b544-45114a66ec16">

**Comment by cth06-Github** [comment]
because no one seems to know who Alex Yeoh or Joanna Carroll is anyway

**Comment by WinstonJin** [comment]
Nope, ill close this
